### ISSUE TITLE
make URLs not ugly

### ISSUE THREAD

**Issue by connorjclark** [paulirish/lh-scorecalc#15]
https://googlechrome.github.io/lighthouse/scorecalc/#first-contentful-paint=2116.062&speed-index=6443.4597264003805&largest-contentful-paint=8090.605999999999&interactive=16512.005999999994&total-blocking-time=1157.7600000000011&cumulative-layout-shift=0.19593750000000001&first-cpu-idle=3952.517464813232&first-meaningful-paint=2116.062&device=mobile&version=6.0.0&version=5.6.0

look how ugly it is. so ugly.

**Comment by paulirish** [comment]
here's the shorter version i've been planning. this good enough?

googlechrome.github.io/lighthouse/scorecalc/#FCP=2116.06&SI=6443.46&LCP=8090.61&TTI=16512.01&TBT=1157.76&CLS=0.2&FCI=3952.52&FMP=2116.06&device=mobile&version=6.0.0&version=5.6.0
