### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Skavr777** [paulirish/lh-scorecalc#30]
const scoring = {
  FCP: {median: 4000, falloff: 2000, name: 'First Contentful Paint'},
  FMP: {median: 4000, falloff: 2000, name: 'First Meaningful Paint'},
  SI: {median: 5800, falloff: 2900, name: 'Speed Index'},
  TTI: {median: 7300, falloff: 2900, name: 'Time to Interactive'},
  FCI: {median: 6500, falloff: 2900, name: 'First CPU Idle'},
  TBT: {median: 600, falloff: 200, name: 'Total Blocking Time'}, // mostly uncalibrated
  LCP: {median: 4000, falloff: 2000, name: 'Largest Contentful Paint'},
  CLS: {median: 0.25, falloff: 0.054, name: 'Cumulative Layout Shift', units: 'unitless'},

Hi,
Is it for mobile or for desktop? 
Can you, please, share the const scoring for mobile and desktop?

**Comment by paulirish** [comment]
https://github.com/paulirish/lh-scorecalc/blob/251d81ea55af139b066afe5e03b6210f05535350/script/metrics.js#L13-L30
