### ISSUE TITLE
[Feature Request] Desktop Curves

### ISSUE THREAD

**Issue by jmdelacerna** [paulirish/lh-scorecalc#7]
Is it possible to request for desktop curves in this calculator? Thank you!

**Comment by paulirish** [comment]
@jmdelacerna thanks for asking. we'll be doing this soon.

**Comment by paulirish** [comment]
This is mostly fixed. You can get desktop scoring with a URL like https://googlechrome.github.io/lighthouse/scorecalc/#device=desktop

Soon, we'll be adding a dropdown UI control to make this more obvious.

**Comment by connorjclark** [comment]
> Soon, we'll be adding a dropdown UI control to make this more obvious.

P1? P2?
